version: '3.8'

services:
  redis:
    image: 'redis:6.2-alpine'
    container_name: 'redis'
    ports:
      - '6379:6379'

  server:
    build: ./server
    container_name: 'server'
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build: ./client
    container_name: 'client'
    ports:
      - '8080:80'
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:3000
